spring.application.name=station-connect
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/stationconnect
spring.datasource.username=sc_user
spring.datasource.password=sc_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true